  odom_frame_id: "odom"
  odom_model_type: "diff-corrected"
  base_frame_id: "robot_footprint"
  global_frame_id: "map"
  transform_tolerance: 0.2

  min_particles: 15
  max_particles: 250

  initial_pose_x: 0.0 # 0.0
  initial_pose_y: 0.0 # 0.0
  initial_pose_a: -0.7853981634 # 0.0 * pi

  update_min_d: 0.2 # 0.2
  update_min_a: 0.5235987756 # pi/6

  recovery_alpha_slow: 0.001
  recovery_alpha_fast: 0.1

  laser_model_type: "likelihood_field_prob"
  laser_min_range: -1.0 # -1.0
  laser_max_range: -1.0 # -1.0
  laser_max_beams: 30 # 30

  laser_z_hit: 0.95 # 0.95
  laser_z_rand: 0.05 # 0.05

  # use_map_topic: true
  odom_alpha1: 0.005 # 0.2
  odom_alpha2: 0.005 # 0.2
  odom_alpha3: 0.010 # 0.2
  odom_alpha4: 0.005 # 0.2


