local_costmap:
   global_frame: odom
   robot_base_frame: robot_footprint
   update_frequency: 3.0
   publish_frequency: 3.0
   width: 40.0
   height: 40.0
   resolution: 0.05
   static_map: false
   rolling_window: true